17. 8. 2016 12:15:05 : GetTracks received parameter : 1
17. 8. 2016 12:15:05 : received tracks from db : 5
17. 8. 2016 12:15:05 : track count : 3
17. 8. 2016 12:15:07 : TRACKID: ba6eb6a0-db7e-48c6-9831-1c391b7be259
17. 8. 2016 12:15:07 : nr of points received: 150
17. 8. 2016 12:15:07 : coordinates returned: [ { "lat":"50,129872", "lng": "14,419802", "time":"2. 5. 2016 19:34:22"},{ "lat":"50,129747", "lng": "14,419718", "time":"2. 5. 2016 19:35:24"},{ "lat":"50,129740", "lng": "14,417965", "time":"2. 5. 2016 19:36:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:37:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:38:24"},{ "lat":"50,130478", "lng": "14,419902", "time":"2. 5. 2016 19:41:19"},{ "lat":"50,130440", "lng": "14,419475", "time":"2. 5. 2016 19:48:37"},{ "lat":"50,128985", "lng": "14,420273", "time":"2. 5. 2016 19:59:51"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:00:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:01:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:02:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:03:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:04:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:05:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:06:52"},{ "lat":"50,129035", "lng": "14,419577", "time":"2. 5. 2016 20:15:34"},{ "lat":"50,129720", "lng": "14,419753", "time":"2. 5. 2016 20:09:59"},{ "lat":"50,129713", "lng": "14,419522", "time":"2. 5. 2016 20:14:33"},{ "lat":"50,128948", "lng": "14,418650", "time":"2. 5. 2016 20:15:51"},{ "lat":"50,129378", "lng": "14,419143", "time":"2. 5. 2016 20:15:56"},{ "lat":"50,129842", "lng": "14,419818", "time":"2. 5. 2016 20:16:51"},{ "lat":"50,130260", "lng": "14,419818", "time":"2. 5. 2016 20:24:19"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:25:46"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:26:46"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:30:41"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:31:41"},{ "lat":"50,130372", "lng": "14,420020", "time":"2. 5. 2016 20:32:52"},{ "lat":"50,130460", "lng": "14,419857", "time":"2. 5. 2016 20:37:00"},{ "lat":"50,130502", "lng": "14,419930", "time":"2. 5. 2016 20:37:19"},{ "lat":"50,130670", "lng": "14,419667", "time":"2. 5. 2016 20:38:00"},{ "lat":"50,129872", "lng": "14,419802", "time":"2. 5. 2016 19:34:22"},{ "lat":"50,129747", "lng": "14,419718", "time":"2. 5. 2016 19:35:24"},{ "lat":"50,129740", "lng": "14,417965", "time":"2. 5. 2016 19:36:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:37:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:38:24"},{ "lat":"50,130478", "lng": "14,419902", "time":"2. 5. 2016 19:41:19"},{ "lat":"50,130440", "lng": "14,419475", "time":"2. 5. 2016 19:48:37"},{ "lat":"50,128985", "lng": "14,420273", "time":"2. 5. 2016 19:59:51"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:00:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:01:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:02:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:03:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:04:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:05:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:06:52"},{ "lat":"50,129035", "lng": "14,419577", "time":"2. 5. 2016 20:15:34"},{ "lat":"50,129720", "lng": "14,419753", "time":"2. 5. 2016 20:09:59"},{ "lat":"50,129713", "lng": "14,419522", "time":"2. 5. 2016 20:14:33"},{ "lat":"50,128948", "lng": "14,418650", "time":"2. 5. 2016 20:15:51"},{ "lat":"50,129378", "lng": "14,419143", "time":"2. 5. 2016 20:15:56"},{ "lat":"50,129842", "lng": "14,419818", "time":"2. 5. 2016 20:16:51"},{ "lat":"50,130260", "lng": "14,419818", "time":"2. 5. 2016 20:24:19"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:25:46"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:26:46"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:30:41"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:31:41"},{ "lat":"50,130372", "lng": "14,420020", "time":"2. 5. 2016 20:32:52"},{ "lat":"50,130460", "lng": "14,419857", "time":"2. 5. 2016 20:37:00"},{ "lat":"50,130502", "lng": "14,419930", "time":"2. 5. 2016 20:37:19"},{ "lat":"50,130670", "lng": "14,419667", "time":"2. 5. 2016 20:38:00"},{ "lat":"50,129872", "lng": "14,419802", "time":"2. 5. 2016 19:34:22"},{ "lat":"50,129747", "lng": "14,419718", "time":"2. 5. 2016 19:35:24"},{ "lat":"50,129740", "lng": "14,417965", "time":"2. 5. 2016 19:36:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:37:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:38:24"},{ "lat":"50,130478", "lng": "14,419902", "time":"2. 5. 2016 19:41:19"},{ "lat":"50,130440", "lng": "14,419475", "time":"2. 5. 2016 19:48:37"},{ "lat":"50,128985", "lng": "14,420273", "time":"2. 5. 2016 19:59:51"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:00:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:01:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:02:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:03:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:04:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:05:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:06:52"},{ "lat":"50,129035", "lng": "14,419577", "time":"2. 5. 2016 20:15:34"},{ "lat":"50,129720", "lng": "14,419753", "time":"2. 5. 2016 20:09:59"},{ "lat":"50,129713", "lng": "14,419522", "time":"2. 5. 2016 20:14:33"},{ "lat":"50,128948", "lng": "14,418650", "time":"2. 5. 2016 20:15:51"},{ "lat":"50,129378", "lng": "14,419143", "time":"2. 5. 2016 20:15:56"},{ "lat":"50,129842", "lng": "14,419818", "time":"2. 5. 2016 20:16:51"},{ "lat":"50,130260", "lng": "14,419818", "time":"2. 5. 2016 20:24:19"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:25:46"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:26:46"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:30:41"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:31:41"},{ "lat":"50,130372", "lng": "14,420020", "time":"2. 5. 2016 20:32:52"},{ "lat":"50,130460", "lng": "14,419857", "time":"2. 5. 2016 20:37:00"},{ "lat":"50,130502", "lng": "14,419930", "time":"2. 5. 2016 20:37:19"},{ "lat":"50,130670", "lng": "14,419667", "time":"2. 5. 2016 20:38:00"},{ "lat":"50,129872", "lng": "14,419802", "time":"2. 5. 2016 19:34:22"},{ "lat":"50,129747", "lng": "14,419718", "time":"2. 5. 2016 19:35:24"},{ "lat":"50,129740", "lng": "14,417965", "time":"2. 5. 2016 19:36:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:37:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:38:24"},{ "lat":"50,130478", "lng": "14,419902", "time":"2. 5. 2016 19:41:19"},{ "lat":"50,130440", "lng": "14,419475", "time":"2. 5. 2016 19:48:37"},{ "lat":"50,128985", "lng": "14,420273", "time":"2. 5. 2016 19:59:51"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:00:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:01:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:02:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:03:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:04:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:05:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:06:52"},{ "lat":"50,129035", "lng": "14,419577", "time":"2. 5. 2016 20:15:34"},{ "lat":"50,129720", "lng": "14,419753", "time":"2. 5. 2016 20:09:59"},{ "lat":"50,129713", "lng": "14,419522", "time":"2. 5. 2016 20:14:33"},{ "lat":"50,128948", "lng": "14,418650", "time":"2. 5. 2016 20:15:51"},{ "lat":"50,129378", "lng": "14,419143", "time":"2. 5. 2016 20:15:56"},{ "lat":"50,129842", "lng": "14,419818", "time":"2. 5. 2016 20:16:51"},{ "lat":"50,130260", "lng": "14,419818", "time":"2. 5. 2016 20:24:19"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:25:46"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:26:46"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:30:41"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:31:41"},{ "lat":"50,130372", "lng": "14,420020", "time":"2. 5. 2016 20:32:52"},{ "lat":"50,130460", "lng": "14,419857", "time":"2. 5. 2016 20:37:00"},{ "lat":"50,130502", "lng": "14,419930", "time":"2. 5. 2016 20:37:19"},{ "lat":"50,130670", "lng": "14,419667", "time":"2. 5. 2016 20:38:00"},{ "lat":"50,129872", "lng": "14,419802", "time":"2. 5. 2016 19:34:22"},{ "lat":"50,129747", "lng": "14,419718", "time":"2. 5. 2016 19:35:24"},{ "lat":"50,129740", "lng": "14,417965", "time":"2. 5. 2016 19:36:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:37:24"},{ "lat":"50,129740", "lng": "14,419965", "time":"2. 5. 2016 19:38:24"},{ "lat":"50,130478", "lng": "14,419902", "time":"2. 5. 2016 19:41:19"},{ "lat":"50,130440", "lng": "14,419475", "time":"2. 5. 2016 19:48:37"},{ "lat":"50,128985", "lng": "14,420273", "time":"2. 5. 2016 19:59:51"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:00:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:01:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:02:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:03:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:04:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:05:52"},{ "lat":"50,129195", "lng": "14,420182", "time":"2. 5. 2016 20:06:52"},{ "lat":"50,129035", "lng": "14,419577", "time":"2. 5. 2016 20:15:34"},{ "lat":"50,129720", "lng": "14,419753", "time":"2. 5. 2016 20:09:59"},{ "lat":"50,129713", "lng": "14,419522", "time":"2. 5. 2016 20:14:33"},{ "lat":"50,128948", "lng": "14,418650", "time":"2. 5. 2016 20:15:51"},{ "lat":"50,129378", "lng": "14,419143", "time":"2. 5. 2016 20:15:56"},{ "lat":"50,129842", "lng": "14,419818", "time":"2. 5. 2016 20:16:51"},{ "lat":"50,130260", "lng": "14,419818", "time":"2. 5. 2016 20:24:19"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:25:46"},{ "lat":"50,130537", "lng": "14,419428", "time":"2. 5. 2016 20:26:46"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:30:41"},{ "lat":"50,130517", "lng": "14,420025", "time":"2. 5. 2016 20:31:41"},{ "lat":"50,130372", "lng": "14,420020", "time":"2. 5. 2016 20:32:52"},{ "lat":"50,130460", "lng": "14,419857", "time":"2. 5. 2016 20:37:00"},{ "lat":"50,130502", "lng": "14,419930", "time":"2. 5. 2016 20:37:19"},{ "lat":"50,130670", "lng": "14,419667", "time":"2. 5. 2016 20:38:00"} ]
8/17/2016 1:08:30 PM : GetTracks received parameter : 1
8/17/2016 1:08:47 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 1:08:47 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 1:08:47 PM : received tracks from db : 0
8/17/2016 1:29:25 PM : GetTracks received parameter : 1
8/17/2016 1:29:30 PM : GetTracks received parameter : 1
8/17/2016 1:29:52 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 1:29:52 PM : received tracks from db : 0
8/17/2016 1:29:52 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 1:29:52 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 2:54:04 PM : GetTracks received parameter : 1
8/17/2016 2:54:34 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
8/17/2016 2:54:34 PM : received tracks from db : 0
8/17/2016 2:54:58 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:19:15 PM : GetTracks received parameter : 1
8/17/2016 4:19:45 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
8/17/2016 4:19:45 PM : received tracks from db : 0
8/17/2016 4:19:53 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:20:06 PM : GetTracks received parameter : 1
8/17/2016 4:20:21 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:20:50 PM : GetTracks received parameter : 1
8/17/2016 4:21:20 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
8/17/2016 4:21:29 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:21:29 PM : received tracks from db : 0
8/17/2016 4:25:28 PM : GetTracks received parameter : 1
8/17/2016 4:25:55 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:26:07 PM : GetTracks received parameter : 1
8/17/2016 4:26:10 PM : DB query failed :  SELECT TOP 1 [ID]  ,[DEVICEID],[TIMESTAMP] ,[LAT] ,[LON], [TRACKCREATED]
  FROM [dbo].[COORDINATES]
  where DEVICEID in (SELECT [DEVICEID]
  FROM [dbo].[CUSTOMER_DEVICE]
  where CUSTOMERID in ( SELECT [CUSTOMERID]
  FROM [dbo].[CUSTOMER_USER]
  where userid in  (SELECT [UserId]
  FROM [dbo].[aspnet_Users]
  where UserName ='Administrator')))
                ORDER BY TIMESTAMP DESC   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:26:10 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:26:10 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:26:10 PM : received tracks from db : 0
8/17/2016 4:31:50 PM : GetTracks received parameter : 1
8/17/2016 4:32:17 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:32:32 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:32:32 PM : received tracks from db : 0
8/17/2016 4:34:32 PM : GetTracks received parameter : 1
8/17/2016 4:35:04 PM : DB query failed :  SELECT TOP 1 [ID]  ,[DEVICEID],[TIMESTAMP] ,[LAT] ,[LON], [TRACKCREATED]
  FROM [dbo].[COORDINATES]
  where DEVICEID in (SELECT [DEVICEID]
  FROM [dbo].[CUSTOMER_DEVICE]
  where CUSTOMERID in ( SELECT [CUSTOMERID]
  FROM [dbo].[CUSTOMER_USER]
  where userid in  (SELECT [UserId]
  FROM [dbo].[aspnet_Users]
  where UserName ='Administrator')))
                ORDER BY TIMESTAMP DESC   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:35:25 PM : GetTracks received parameter : 1
8/17/2016 4:35:31 PM : GetTracks received parameter : 1
8/17/2016 4:36:09 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:36:09 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:36:09 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:36:09 PM : received tracks from db : 0
8/17/2016 4:36:09 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:36:09 PM : DB query failed :  SELECT TOP 1 [ID]  ,[DEVICEID],[TIMESTAMP] ,[LAT] ,[LON], [TRACKCREATED]
  FROM [dbo].[COORDINATES]
  where DEVICEID in (SELECT [DEVICEID]
  FROM [dbo].[CUSTOMER_DEVICE]
  where CUSTOMERID in ( SELECT [CUSTOMERID]
  FROM [dbo].[CUSTOMER_USER]
  where userid in  (SELECT [UserId]
  FROM [dbo].[aspnet_Users]
  where UserName ='Administrator')))
                ORDER BY TIMESTAMP DESC   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:36:09 PM : received tracks from db : 0
8/17/2016 4:38:13 PM : GetTracks received parameter : 1
8/17/2016 4:38:22 PM : GetTracks received parameter : 1
8/17/2016 4:38:30 PM : GetTracks received parameter : 1
8/17/2016 4:38:40 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : DB query failed :  SELECT TOP 1 [ID]  ,[DEVICEID],[TIMESTAMP] ,[LAT] ,[LON], [TRACKCREATED]
  FROM [dbo].[COORDINATES]
  where DEVICEID in (SELECT [DEVICEID]
  FROM [dbo].[CUSTOMER_DEVICE]
  where CUSTOMERID in ( SELECT [CUSTOMERID]
  FROM [dbo].[CUSTOMER_USER]
  where userid in  (SELECT [UserId]
  FROM [dbo].[aspnet_Users]
  where UserName ='Administrator')))
                ORDER BY TIMESTAMP DESC   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : received tracks from db : 0
8/17/2016 4:38:40 PM : DB query failed :  SELECT TOP 1 [ID]  ,[DEVICEID],[TIMESTAMP] ,[LAT] ,[LON], [TRACKCREATED]
  FROM [dbo].[COORDINATES]
  where DEVICEID in (SELECT [DEVICEID]
  FROM [dbo].[CUSTOMER_DEVICE]
  where CUSTOMERID in ( SELECT [CUSTOMERID]
  FROM [dbo].[CUSTOMER_USER]
  where userid in  (SELECT [UserId]
  FROM [dbo].[aspnet_Users]
  where UserName ='Administrator')))
                ORDER BY TIMESTAMP DESC   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:38:40 PM : received tracks from db : 0
8/17/2016 4:41:42 PM : GetTracks received parameter : 1
8/17/2016 4:42:12 PM : DB query failed :  SELECT COUNT(*)
  FROM [dbo].[TRACKS] as tracks, dbo.CUSTOMER_DEVICE as CD, 
  dbo.CUSTOMER_USER as CU, dbo.aspnet_Users as U
WHERE CD.DEVICEID = tracks.DEVICEID AND CD.CUSTOMERID = CU.CUSTOMERID 
AND CU.USERID = U.UserId AND U.UserName ='Administrator'   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
8/17/2016 4:42:12 PM : received tracks from db : 0
8/17/2016 4:42:12 PM : DB query failed :  SELECT TOP 1 [ID]  ,[DEVICEID],[TIMESTAMP] ,[LAT] ,[LON], [TRACKCREATED]
  FROM [dbo].[COORDINATES]
  where DEVICEID in (SELECT [DEVICEID]
  FROM [dbo].[CUSTOMER_DEVICE]
  where CUSTOMERID in ( SELECT [CUSTOMERID]
  FROM [dbo].[CUSTOMER_USER]
  where userid in  (SELECT [UserId]
  FROM [dbo].[aspnet_Users]
  where UserName ='Administrator')))
                ORDER BY TIMESTAMP DESC   System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at BootstrapAspNetApp.MyDatabase.QueryWrapper(String query, String TableName) in d:\AAA_GIT\chytreauto\BootstrapAspNetApp\BootstrapAspNetApp\Database.cs:line 52
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
